# Generated by Django 4.0.5 on 2022-06-27 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfWords',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word1', models.CharField(max_length=30)),
                ('word2', models.CharField(max_length=30)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('group', models.ManyToManyField(related_name='words', to='words.groupofwords')),
            ],
        ),
    ]
