# Generated by Django 4.0.5 on 2022-07-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofwords',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word1',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
