# Generated by Django 4.0.5 on 2022-06-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_groupofwords_word_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='words.groupofwords'),
        ),
    ]
