# Generated by Django 4.0.5 on 2022-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='group',
        ),
        migrations.AddField(
            model_name='word',
            name='group',
            field=models.ManyToManyField(related_name='words', to='words.groupofwords'),
        ),
    ]
