# Generated by Django 4.0.5 on 2022-07-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='general_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.groupofwords'),
        ),
    ]
